name: drone-test
kind: pipeline
type: docker

steps:
  - name: test
    image: golang:1.18-alpine
    volumes:
      - name: deps
        path: /go
    commands:
      - CGO_ENABLED=0 go test

  - name: build
    image: golang:1.18-alpine
    volumes:
      - name: deps
        path: /go
    commands:
      - CGO_ENABLED=0 go build

  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: shivaluma/drone-test

volumes:
  - name: deps
    temp: {}
