name: drone-test
kind: pipeline
type: docker

steps:
  - name: test
    image: golang:1.18-alpine
    volumes:
      - name: deps
        path: /go
    commands:
      - CGO_ENABLED=0 go test

  - name: build
    image: golang:1.18-alpine
    volumes:
      - name: deps
        path: /go
    commands:
      - CGO_ENABLED=0 go build

volumes:
  - name: deps
    temp: {}
